config/routes.rb
Aineui::Application.routes.draw do
  resources :user_machines

  resources :vmconfigs

  resources :vm_configs

  root :to => 'user_sessions#new'
  
  resources :users

  resources :os_images

  resources :servers

  resources :snapshots

  resources :virtual_machines

  Aineui::Application.routes.draw do
  resources :vmconfigs

    resources :users, :user_sessions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
  end

  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/vmconfig.rb
class Vmconfig < ActiveRecord::Base
  attr_accessible :memory, :vcpu, :description, :name
  has_many :virtual_machines
end

app/controllers/vmconfigs_controller.rb
class VmconfigsController < ApplicationController
  # GET /vmconfigs
  # GET /vmconfigs.json
  def index
    @vmconfigs = Vmconfig.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vmconfigs }
    end
  end

  # GET /vmconfigs/1
  # GET /vmconfigs/1.json
  def show
    @vmconfig = Vmconfig.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vmconfig }
    end
  end

  # GET /vmconfigs/new
  # GET /vmconfigs/new.json
  def new
    @vmconfig = Vmconfig.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vmconfig }
    end
  end

  # GET /vmconfigs/1/edit
  def edit
    @vmconfig = Vmconfig.find(params[:id])
  end

  # POST /vmconfigs
  # POST /vmconfigs.json
  def create
    @vmconfig = Vmconfig.new(params[:vmconfig])

    respond_to do |format|
      if @vmconfig.save
        format.html { redirect_to @vmconfig, notice: 'Vmconfig was successfully created.' }
        format.json { render json: @vmconfig, status: :created, location: @vmconfig }
      else
        format.html { render action: "new" }
        format.json { render json: @vmconfig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vmconfigs/1
  # PUT /vmconfigs/1.json
  def update
    @vmconfig = Vmconfig.find(params[:id])

    respond_to do |format|
      if @vmconfig.update_attributes(params[:vmconfig])
        format.html { redirect_to @vmconfig, notice: 'Vmconfig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vmconfig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vmconfigs/1
  # DELETE /vmconfigs/1.json
  def destroy
    @vmconfig = Vmconfig.find(params[:id])
    @vmconfig.destroy

    respond_to do |format|
      format.html { redirect_to vmconfigs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/vmconfigs_helper.rb
module VmconfigsHelper
end

app/views/vmconfigs/_form.html.erb
<%= form_for @vmconfig, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :memory, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :memory, :class => 'text_area' %>
    </div>
  </div>
   <div class="control-group">
    <%= f.label :vcpu, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :vcpu, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                vmconfigs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/vmconfigs/edit.html.erb
<%- model_class = Vmconfig -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vmconfigs/index.html.erb
<%- model_class = Vmconfig -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:memory) %></th>
      <th><%= model_class.human_attribute_name(:vcpu) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vmconfigs.each do |vmconfig| %>
      <tr>
        <td><%= link_to vmconfig.id, vmconfig_path(vmconfig) %></td>
        <td><%= vmconfig.name %></td>
        <td><%= vmconfig.description %></td>
        <td><%= vmconfig.memory %></td>
        <td><%= vmconfig.vcpu %></td>
        <td><%=l vmconfig.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vmconfig_path(vmconfig), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vmconfig_path(vmconfig),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_vmconfig_path,
            :class => 'btn btn-primary' %>

app/views/vmconfigs/new.html.erb
<%- model_class = Vmconfig -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vmconfigs/show.html.erb
<%- model_class = Vmconfig -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @vmconfig.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @vmconfig.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:memory) %>:</strong></dt>
  <dd><%= @vmconfig.memory %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vcpu) %>:</strong></dt>
  <dd><%= @vmconfig.vcpu %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              vmconfigs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vmconfig_path(@vmconfig), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vmconfig_path(@vmconfig),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>