config/routes.rb
Aineui::Application.routes.draw do
  resources :user_machines

  resources :vmconfigs

  resources :vm_configs

  root :to => 'user_sessions#new'
  
  resources :users

  resources :os_images

  resources :servers

  resources :snapshots

  resources :virtual_machines

  Aineui::Application.routes.draw do
  resources :vmconfigs

    resources :users, :user_sessions
    match 'login' => 'user_sessions#new', :as => :login
    match 'logout' => 'user_sessions#destroy', :as => :logout
  end

  

  match ':controller(/:action(/:id))(.:format)'
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
	def to_key
		new_record? ? nil : [ self.send(self.class.primary_key) ]
	end
	def persisted?
		false
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  # GET /user_sessions
  # GET /user_sessions.json
  def new
    @user_session = UserSession.new
 
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @user_session }
    end
  end
 
  # POST /user_sessions
  # POST /user_sessions.xml
  def create
    @user_session = UserSession.new(params[:user_session])
     
    respond_to do |format|
      if @user_session.save
        format.html { redirect_to(:virtual_machines, :notice => 'Login Successful') }
        format.xml { render :xml => @user_session, :status => :created, :location => @user_session }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end
 
  # DELETE /user_sessions/1
  # DELETE /user_sessions/1.xml
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
     
    respond_to do |format|
      format.html { redirect_to(:login, :notice => 'Goodbye!') }
      format.xml { head :ok }
    end
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_for(@user_session) do |f| %>
  <div class="form-actions">
  <% if @user_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited this user_session from being saved:</h2>

      <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  
    <%= f.submit "Login", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/user_sessions/edit.html.erb
<h1>Editing user_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_session %> |
<%= link_to 'Back', user_sessions_path %>

app/views/user_sessions/index.html.erb
<h1>Listing user_sessions</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_sessions.each do |user_session| %>
  <tr>
    <td><%= user_session.username %></td>
    <td><%= user_session.password %></td>
    <td><%= link_to 'Show', user_session %></td>
    <td><%= link_to 'Edit', edit_user_session_path(user_session) %></td>
    <td><%= link_to 'Destroy', user_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User session', new_user_session_path %>

app/views/user_sessions/new.html.erb
<div class="span3 offset4">
<h3>Login to proceed!</h3>

<%= render 'form' %>
</div>

app/views/user_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user_session.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user_session.password %>
</p>


<%= link_to 'Edit', edit_user_session_path(@user_session) %> |
<%= link_to 'Back', user_sessions_path %>